application: twcurrency
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /rate.*
  script: main.app
- url: /tasks/.*
  script: main.app
  login: admin
- url: /static/css
  static_dir: static/css
  expiration: "7d"


libraries:
- name: lxml
  version: latest

