application: twcurrency
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /rate.*
  script: main.app
  login: admin
- url: /tasks/.*
  script: main.app
  login: admin

libraries:
- name: lxml
  version: latest

