application: twcurrency
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: lxml
  version: latest
#- name: jinja2
#  version: latest

